{{- if and .Values.management.enabled .Values.management.configmap (ne .Values.management.configmap "") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
data:
  management.json: |-
    {{- .Values.management.configmap | nindent 4 }}
{{- end -}}
